### ISSUE TITLE
[Question] Warning on cannot find js-bson

### ISSUE THREAD

**Issue by runlevel5** [toymachiner62/mongo-factory#2]
I am on `mongodb` driver `2.0.43` atm, and I got this when my expressjs starts:

```
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
```

I am wondering if this is related to this package only

**Comment by toymachiner62** [comment]
I get that on a lot of projects too. I do not believe it is directly related to mongo-factory. May be caused by one of it's dependencies. I don't think it hurts anything though as it looks like as a backup it uses a pure JS version.
