### ISSUE TITLE
MongoError: "Topology was destroyed"

### ISSUE THREAD

**Issue by sohaibfarooqi** [toymachiner62/mongo-factory#4]
Hi,
I require this module in two different file that runs concurrently. Both module uses same connection string. I am getting this error. Any workaround for this?

EDIT: I am calling db.close(); at the end of processing. Might this be an issue?

**Comment by toymachiner62** [comment]
Yes i'm guessing that's the problem. If you look at this question http://stackoverflow.com/questions/30909492/mongoerror-topology-was-destroyed it seems that error means that the connection was interrupted while trying to write.

**Comment by sohaibfarooqi** [comment]
Yes I have removed `db.close();` and it is working good.
